version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5252:5252" # Set via .env
      - "8989:8989" # Default in main.rs
    depends_on:
      - postgres

  postgres:
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpasswd
      POSTGRES_DB: vrtstorage
    ports:
      - "5431:5432"  # Expose PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:  # Define a named volume for PostgreSQL data
